apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: platform-service # Must match the labels on your Pods
  ports:
    - protocol: TCP
      port: 80 # The port the Service itself exposes
      targetPort: 8080 # The port the container is listening on
      nodePort: 31189 # Optional: Kubernetes assigns one automatically if omitted
