apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-service
  template:
    metadata:
      labels:
        app: platform-service
    spec:
      containers:
        - name: platform-service
          image: douglasvincent/platformservice:latest
          imagePullPolicy: Always
          env:
            - name: ConnectionStrings__PlatformsDatabase
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: ConnectionStrings__PlatformsDatabase
          
---
apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platform-service
  ports:
    - name: platform-service
      protocol: TCP
      port: 80
      targetPort: 80
    - name: platform-grpc
      protocol: TCP
      port: 680
      targetPort: 680